#!/usr/bin/python
import sys
from subprocess import Popen, PIPE

def get_cols():
	#so = Popen(["/bin/stty", "size"], stdout=PIPE).communicate()[0]
	#rows, cols = map(int, so.split())
	#return cols
	return 24, 80

def ruler(cols):

	w = 5
	r = cols/w

	for n in xrange(r):
		v = 100 * n / r
		vs = "%d" % (v,)
		sys.stdout.write(vs + '.' * (w - len(vs)))
	sys.stdout.write("\n")

def main():
	rows, cols = get_cols()
	linen = 0


	while True:
		line = raw_input()
		if line.startswith('#'):
			continue

		if linen % rows == 0:
			ruler(cols)

		f = map(float, line.split())
		util = f[1]

		length = int(util*cols/100.0)
		sys.stdout.write(' '*(length-1))
		sys.stdout.write('X\n')
		sys.stdout.flush()

		linen += 1
	
main()
